name: Fase 2 DevOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        IMAGE_TAG=my-image-name:$(date +%s)
        docker build ./docker --file ./docker/Dockerfile --tag $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Save Docker image as tar
      run: docker save $IMAGE_TAG -o fase2-app.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: fase2-app.tar
